parameters:
#    petit_back.example.class: Petit\BackBundle\Example

services:
#    petit_back.example:
#        class: %petit_back.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
